// Code generated by counterfeiter. DO NOT EDIT.
package credhubfakes

import (
	"sync"

	"code.cloudfoundry.org/credhub-cli/credhub/credentials"
	"code.cloudfoundry.org/credhub-cli/credhub/credentials/values"
	"github.com/orange-cloudfoundry/terraform-secure-backend/server/credhub"
)

type FakeCredhubClient struct {
	DeleteStub        func(string) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 string
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	FindByPathStub        func(string) (credentials.FindResults, error)
	findByPathMutex       sync.RWMutex
	findByPathArgsForCall []struct {
		arg1 string
	}
	findByPathReturns struct {
		result1 credentials.FindResults
		result2 error
	}
	findByPathReturnsOnCall map[int]struct {
		result1 credentials.FindResults
		result2 error
	}
	GetLatestJSONStub        func(string) (credentials.JSON, error)
	getLatestJSONMutex       sync.RWMutex
	getLatestJSONArgsForCall []struct {
		arg1 string
	}
	getLatestJSONReturns struct {
		result1 credentials.JSON
		result2 error
	}
	getLatestJSONReturnsOnCall map[int]struct {
		result1 credentials.JSON
		result2 error
	}
	GetLatestValueStub        func(string) (credentials.Value, error)
	getLatestValueMutex       sync.RWMutex
	getLatestValueArgsForCall []struct {
		arg1 string
	}
	getLatestValueReturns struct {
		result1 credentials.Value
		result2 error
	}
	getLatestValueReturnsOnCall map[int]struct {
		result1 credentials.Value
		result2 error
	}
	SetJSONStub        func(string, values.JSON) (credentials.JSON, error)
	setJSONMutex       sync.RWMutex
	setJSONArgsForCall []struct {
		arg1 string
		arg2 values.JSON
	}
	setJSONReturns struct {
		result1 credentials.JSON
		result2 error
	}
	setJSONReturnsOnCall map[int]struct {
		result1 credentials.JSON
		result2 error
	}
	SetValueStub        func(string, values.Value) (credentials.Value, error)
	setValueMutex       sync.RWMutex
	setValueArgsForCall []struct {
		arg1 string
		arg2 values.Value
	}
	setValueReturns struct {
		result1 credentials.Value
		result2 error
	}
	setValueReturnsOnCall map[int]struct {
		result1 credentials.Value
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCredhubClient) Delete(arg1 string) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("Delete", []interface{}{arg1})
	fake.deleteMutex.Unlock()
	if fake.DeleteStub != nil {
		return fake.DeleteStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.deleteReturns
	return fakeReturns.result1
}

func (fake *FakeCredhubClient) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeCredhubClient) DeleteCalls(stub func(string) error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *FakeCredhubClient) DeleteArgsForCall(i int) string {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCredhubClient) DeleteReturns(result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCredhubClient) DeleteReturnsOnCall(i int, result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCredhubClient) FindByPath(arg1 string) (credentials.FindResults, error) {
	fake.findByPathMutex.Lock()
	ret, specificReturn := fake.findByPathReturnsOnCall[len(fake.findByPathArgsForCall)]
	fake.findByPathArgsForCall = append(fake.findByPathArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("FindByPath", []interface{}{arg1})
	fake.findByPathMutex.Unlock()
	if fake.FindByPathStub != nil {
		return fake.FindByPathStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.findByPathReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCredhubClient) FindByPathCallCount() int {
	fake.findByPathMutex.RLock()
	defer fake.findByPathMutex.RUnlock()
	return len(fake.findByPathArgsForCall)
}

func (fake *FakeCredhubClient) FindByPathCalls(stub func(string) (credentials.FindResults, error)) {
	fake.findByPathMutex.Lock()
	defer fake.findByPathMutex.Unlock()
	fake.FindByPathStub = stub
}

func (fake *FakeCredhubClient) FindByPathArgsForCall(i int) string {
	fake.findByPathMutex.RLock()
	defer fake.findByPathMutex.RUnlock()
	argsForCall := fake.findByPathArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCredhubClient) FindByPathReturns(result1 credentials.FindResults, result2 error) {
	fake.findByPathMutex.Lock()
	defer fake.findByPathMutex.Unlock()
	fake.FindByPathStub = nil
	fake.findByPathReturns = struct {
		result1 credentials.FindResults
		result2 error
	}{result1, result2}
}

func (fake *FakeCredhubClient) FindByPathReturnsOnCall(i int, result1 credentials.FindResults, result2 error) {
	fake.findByPathMutex.Lock()
	defer fake.findByPathMutex.Unlock()
	fake.FindByPathStub = nil
	if fake.findByPathReturnsOnCall == nil {
		fake.findByPathReturnsOnCall = make(map[int]struct {
			result1 credentials.FindResults
			result2 error
		})
	}
	fake.findByPathReturnsOnCall[i] = struct {
		result1 credentials.FindResults
		result2 error
	}{result1, result2}
}

func (fake *FakeCredhubClient) GetLatestJSON(arg1 string) (credentials.JSON, error) {
	fake.getLatestJSONMutex.Lock()
	ret, specificReturn := fake.getLatestJSONReturnsOnCall[len(fake.getLatestJSONArgsForCall)]
	fake.getLatestJSONArgsForCall = append(fake.getLatestJSONArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("GetLatestJSON", []interface{}{arg1})
	fake.getLatestJSONMutex.Unlock()
	if fake.GetLatestJSONStub != nil {
		return fake.GetLatestJSONStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getLatestJSONReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCredhubClient) GetLatestJSONCallCount() int {
	fake.getLatestJSONMutex.RLock()
	defer fake.getLatestJSONMutex.RUnlock()
	return len(fake.getLatestJSONArgsForCall)
}

func (fake *FakeCredhubClient) GetLatestJSONCalls(stub func(string) (credentials.JSON, error)) {
	fake.getLatestJSONMutex.Lock()
	defer fake.getLatestJSONMutex.Unlock()
	fake.GetLatestJSONStub = stub
}

func (fake *FakeCredhubClient) GetLatestJSONArgsForCall(i int) string {
	fake.getLatestJSONMutex.RLock()
	defer fake.getLatestJSONMutex.RUnlock()
	argsForCall := fake.getLatestJSONArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCredhubClient) GetLatestJSONReturns(result1 credentials.JSON, result2 error) {
	fake.getLatestJSONMutex.Lock()
	defer fake.getLatestJSONMutex.Unlock()
	fake.GetLatestJSONStub = nil
	fake.getLatestJSONReturns = struct {
		result1 credentials.JSON
		result2 error
	}{result1, result2}
}

func (fake *FakeCredhubClient) GetLatestJSONReturnsOnCall(i int, result1 credentials.JSON, result2 error) {
	fake.getLatestJSONMutex.Lock()
	defer fake.getLatestJSONMutex.Unlock()
	fake.GetLatestJSONStub = nil
	if fake.getLatestJSONReturnsOnCall == nil {
		fake.getLatestJSONReturnsOnCall = make(map[int]struct {
			result1 credentials.JSON
			result2 error
		})
	}
	fake.getLatestJSONReturnsOnCall[i] = struct {
		result1 credentials.JSON
		result2 error
	}{result1, result2}
}

func (fake *FakeCredhubClient) GetLatestValue(arg1 string) (credentials.Value, error) {
	fake.getLatestValueMutex.Lock()
	ret, specificReturn := fake.getLatestValueReturnsOnCall[len(fake.getLatestValueArgsForCall)]
	fake.getLatestValueArgsForCall = append(fake.getLatestValueArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("GetLatestValue", []interface{}{arg1})
	fake.getLatestValueMutex.Unlock()
	if fake.GetLatestValueStub != nil {
		return fake.GetLatestValueStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getLatestValueReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCredhubClient) GetLatestValueCallCount() int {
	fake.getLatestValueMutex.RLock()
	defer fake.getLatestValueMutex.RUnlock()
	return len(fake.getLatestValueArgsForCall)
}

func (fake *FakeCredhubClient) GetLatestValueCalls(stub func(string) (credentials.Value, error)) {
	fake.getLatestValueMutex.Lock()
	defer fake.getLatestValueMutex.Unlock()
	fake.GetLatestValueStub = stub
}

func (fake *FakeCredhubClient) GetLatestValueArgsForCall(i int) string {
	fake.getLatestValueMutex.RLock()
	defer fake.getLatestValueMutex.RUnlock()
	argsForCall := fake.getLatestValueArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCredhubClient) GetLatestValueReturns(result1 credentials.Value, result2 error) {
	fake.getLatestValueMutex.Lock()
	defer fake.getLatestValueMutex.Unlock()
	fake.GetLatestValueStub = nil
	fake.getLatestValueReturns = struct {
		result1 credentials.Value
		result2 error
	}{result1, result2}
}

func (fake *FakeCredhubClient) GetLatestValueReturnsOnCall(i int, result1 credentials.Value, result2 error) {
	fake.getLatestValueMutex.Lock()
	defer fake.getLatestValueMutex.Unlock()
	fake.GetLatestValueStub = nil
	if fake.getLatestValueReturnsOnCall == nil {
		fake.getLatestValueReturnsOnCall = make(map[int]struct {
			result1 credentials.Value
			result2 error
		})
	}
	fake.getLatestValueReturnsOnCall[i] = struct {
		result1 credentials.Value
		result2 error
	}{result1, result2}
}

func (fake *FakeCredhubClient) SetJSON(arg1 string, arg2 values.JSON) (credentials.JSON, error) {
	fake.setJSONMutex.Lock()
	ret, specificReturn := fake.setJSONReturnsOnCall[len(fake.setJSONArgsForCall)]
	fake.setJSONArgsForCall = append(fake.setJSONArgsForCall, struct {
		arg1 string
		arg2 values.JSON
	}{arg1, arg2})
	fake.recordInvocation("SetJSON", []interface{}{arg1, arg2})
	fake.setJSONMutex.Unlock()
	if fake.SetJSONStub != nil {
		return fake.SetJSONStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.setJSONReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCredhubClient) SetJSONCallCount() int {
	fake.setJSONMutex.RLock()
	defer fake.setJSONMutex.RUnlock()
	return len(fake.setJSONArgsForCall)
}

func (fake *FakeCredhubClient) SetJSONCalls(stub func(string, values.JSON) (credentials.JSON, error)) {
	fake.setJSONMutex.Lock()
	defer fake.setJSONMutex.Unlock()
	fake.SetJSONStub = stub
}

func (fake *FakeCredhubClient) SetJSONArgsForCall(i int) (string, values.JSON) {
	fake.setJSONMutex.RLock()
	defer fake.setJSONMutex.RUnlock()
	argsForCall := fake.setJSONArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCredhubClient) SetJSONReturns(result1 credentials.JSON, result2 error) {
	fake.setJSONMutex.Lock()
	defer fake.setJSONMutex.Unlock()
	fake.SetJSONStub = nil
	fake.setJSONReturns = struct {
		result1 credentials.JSON
		result2 error
	}{result1, result2}
}

func (fake *FakeCredhubClient) SetJSONReturnsOnCall(i int, result1 credentials.JSON, result2 error) {
	fake.setJSONMutex.Lock()
	defer fake.setJSONMutex.Unlock()
	fake.SetJSONStub = nil
	if fake.setJSONReturnsOnCall == nil {
		fake.setJSONReturnsOnCall = make(map[int]struct {
			result1 credentials.JSON
			result2 error
		})
	}
	fake.setJSONReturnsOnCall[i] = struct {
		result1 credentials.JSON
		result2 error
	}{result1, result2}
}

func (fake *FakeCredhubClient) SetValue(arg1 string, arg2 values.Value) (credentials.Value, error) {
	fake.setValueMutex.Lock()
	ret, specificReturn := fake.setValueReturnsOnCall[len(fake.setValueArgsForCall)]
	fake.setValueArgsForCall = append(fake.setValueArgsForCall, struct {
		arg1 string
		arg2 values.Value
	}{arg1, arg2})
	fake.recordInvocation("SetValue", []interface{}{arg1, arg2})
	fake.setValueMutex.Unlock()
	if fake.SetValueStub != nil {
		return fake.SetValueStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.setValueReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCredhubClient) SetValueCallCount() int {
	fake.setValueMutex.RLock()
	defer fake.setValueMutex.RUnlock()
	return len(fake.setValueArgsForCall)
}

func (fake *FakeCredhubClient) SetValueCalls(stub func(string, values.Value) (credentials.Value, error)) {
	fake.setValueMutex.Lock()
	defer fake.setValueMutex.Unlock()
	fake.SetValueStub = stub
}

func (fake *FakeCredhubClient) SetValueArgsForCall(i int) (string, values.Value) {
	fake.setValueMutex.RLock()
	defer fake.setValueMutex.RUnlock()
	argsForCall := fake.setValueArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCredhubClient) SetValueReturns(result1 credentials.Value, result2 error) {
	fake.setValueMutex.Lock()
	defer fake.setValueMutex.Unlock()
	fake.SetValueStub = nil
	fake.setValueReturns = struct {
		result1 credentials.Value
		result2 error
	}{result1, result2}
}

func (fake *FakeCredhubClient) SetValueReturnsOnCall(i int, result1 credentials.Value, result2 error) {
	fake.setValueMutex.Lock()
	defer fake.setValueMutex.Unlock()
	fake.SetValueStub = nil
	if fake.setValueReturnsOnCall == nil {
		fake.setValueReturnsOnCall = make(map[int]struct {
			result1 credentials.Value
			result2 error
		})
	}
	fake.setValueReturnsOnCall[i] = struct {
		result1 credentials.Value
		result2 error
	}{result1, result2}
}

func (fake *FakeCredhubClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	fake.findByPathMutex.RLock()
	defer fake.findByPathMutex.RUnlock()
	fake.getLatestJSONMutex.RLock()
	defer fake.getLatestJSONMutex.RUnlock()
	fake.getLatestValueMutex.RLock()
	defer fake.getLatestValueMutex.RUnlock()
	fake.setJSONMutex.RLock()
	defer fake.setJSONMutex.RUnlock()
	fake.setValueMutex.RLock()
	defer fake.setValueMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCredhubClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ credhub.CredhubClient = new(FakeCredhubClient)
